syntax = "proto3";

import "google/protobuf/timestamp.proto";

package org.nexus.base.proto;

option optimize_for = SPEED;

message Ping {
  uint32 ping = 1; // used to keep track of the number of pings between peers
}

message Manifest {
  bytes cid = 1; // signed manifest id
  string category = 2; // manifest category
  bytes public_key = 3;
}

message GetManifestContent { // request a manifest content based on CID
    bytes cid = 1; // signed manifest id used to ask the network 
}

message ManifestContent { // actual content
    bytes cid = 1;  // signed owner manifest cid
    bytes raw = 2; // raw manifest content
}

message GetPeers {
  uint32 size = 2; // get required number of actives peers from a peer, protects system from flooding from bad actors
  bytes cid = 1; // signed manifest id
  string category = 3; // manifest category      
}

message GetPeersResponse {
      repeated string addresses = 3;
}

// still trying to understand this fully
message Call {
  string api_id = 1;
  bytes params = 3; // fixed numbering (no gaps)
  Result response = 4;
}

message Result {
  uint32 status = 1;  // 0=OK, 1=Error
  string message = 2;
  bytes response_data = 3;
}

message NexusMessage {
  oneof payload {
    Manifest manifest   = 1;
    Ping ping   = 2;
    GetPeersResponse peers = 3;
    Call functionCall = 4;
    GetManifestContent getManifestContent = 5;
    ManifestContent manifestContent = 6;
    GetPeers peersDiscovery = 7;
    Challenge handshake = 8; // handshake protocol
    ChallengeResponse handshakeResponse = 9; // handshake challenge response
  
  }
}

// initiate handshake with a nonce challenge
message Challenge {
    fixed64 nonce = 1;
    fixed64 genesisHash = 2;
}

// handshake challenge response
message ChallengeResponse {
    bytes public_key = 1;
    fixed64 nonce = 2;
}

// size matters
// UUID (128 bits / 16 bytes)
// long (64 bits / 8 bytes) 
// That’s 8 bytes saved per ID. Since you have 2 IDs (node + message), you save 16 bytes per message.
// Example:
// If your average message is ~125 bytes 
// With UUIDs → 125 bytes
// With longs → ~109 bytes
// That’s about 13% smaller messages. Over millions of messages, that’s a real bandwidth and memory difference.
// TODO: optimize payload sizes
message NexusEnvelop {
    bytes node_id = 2; // node id, would have to do some research how this would matter from a peer to peer network point of view
    bytes message_id = 3;     // UUID as string but should be reduced to a 8 bytes
    NexusMessage message = 4;        // optional message-specific payload
    bytes checksum = 5;       // first 4 bytes of double SHA-256(payload)    should be smaller as well
    google.protobuf.Timestamp time_stamp = 6;// request and response time stamp
    bytes signature = 11;          // signature over manifest (except signature field)
}